config/routes.rb
Flixter::Application.routes.draw do
  devise_for :users

  resource :dashboard, only: [:show]
  
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'

  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  
  resources :lessons, only: [:show]

  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update]

    resources :sections, only: [] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all.order(:id)
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show]

  def show
    # @course = Course.find(params[:id])
    #    ^ removed b/c we refactored @course into .current_course
    #      and now the view calls .current_course, so having it here
    #      would be redundant
    @section = Section.new
    #    ^ added when decided to move the new section form into a modal window
    #      on the instructor/courses#show page
    @lesson = Lesson.new
    #    ^ added when decided to move the new lesson form into a modal window
    #      on the instructor/courses#show page
  end

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end


  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render text: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_course

  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  # authenticate_user! is a helper method provided by devise gem
  # ensures user is a logged-in user before running any actions
  before_action :authenticate_user!
  # triggers private methods defined below
  before_action :require_authorization_for_current_section, only: [:create]
  before_action :require_authorization_for_current_lesson, only: [:update]

  def new
    # first
    # load the section that is being referenced
    # in the URL, by pulling the section_id from the params
    # (triggers the private method current_section)
    # @section = Section.find(params[:section_id])
    # @section = current_section
    #    ^ used to have the above as the first step, but now that the 
    #      'new' view was edited to call .current_section instead of @section,
    #      we can remove this explicit first step
    # second
    # build a new empty lesson to give the form a template object
    #@lesson = Lesson.new
    #    ^ removed after we moved the form for creating a new lesson into a modal window
    #      on the instructor/courses#show page, then removed the route that gave us an 
    #      instructor/lessons#new page
  end

  def create
    # first
    # look up the section in the DB that the lesson is for
    # @section = current_section
    #    ^ used to have the above as the first step, but now that the 
    #      'new' view was edited to call .current_section instead of @section,
    #      we can remove this explicit first step
    # create the lesson in the DB & connect it to the section we looked up
    @lesson = current_section.lessons.create(lesson_params)
    # last
    # redirect the user to the instructor dashboard
    redirect_to instructor_course_path(current_section.course)
  end

  # this method is for the drag-and-drop lesson reordering
  # this exposes an endpoint that will allow us to trigger a data update to a 
  #    lesson (ex. update the value of :row_order_position)
  # b/c of the route associated with instructor/lessons#update, it means
  # our app is listening for PUT requests to the instructor_lesson_path, 
  # which will trigger this update action
  def update
    current_lesson.update_attributes(lesson_params)
    render text: 'updated!'
  end

  private

  # same idea as require_auth below, but matches lesson creator to current_user
  def require_authorization_for_current_lesson
    if current_lesson.section.course.user != current_user
      return render text: 'Unathorized', status: :unauthorized
    end
  end

  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

  # ensures logged-in user id (current_user) matches id of user who created course
  def require_authorization_for_current_section
    # (current_section.course.user grabs the course from the section, and the user from the course)
    if current_section.course.user != current_user
      # if mismatch, send 401 status & error message to web browser
      return render text: 'Unathorized', status: :unauthorized
    end
  end

  # declares a helper method to Rails, which will let us call it in our views
  helper_method :current_section

  def current_section
    @current_section ||= Section.find(params[:section_id])
    # ^ line above is same as if/end statement below
    # basically says:
    #     if we've looked up the current_section beforehand,
    #     use the value that we looked up previously. If we haven't 
    #     looked up this section before, go into the database, 
    #     look it up and also make sure to remember the value in 
    #     case we need to look it up again later. This technique of storing 
    #     certain values inside of the memory to reduce the times we have to 
    #     find a certain value inside the database is called memoization

    # if @current_section == nil
    #   @current_section = Section.find(params[:section_id])
    #   @current_section
    # else
    #   @current_section
    # end
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end
end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:create]
  before_action :require_authorized_for_current_section, only: [:update]

  ### removed after we moved the form for creating a new section into a modal window
  ### on the instructor/courses#show page, then removed the route that gave us an 
  ### instructor/sections#new page
  # def new
  #   @section = Section.new
  # end

  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

  def update
    current_section.update_attributes(section_params)
    render text: 'updated!'
  end


  private

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      render text: 'Unauthorized', status: :Unauthorized
    end
  end

  def current_section
    @current_section ||= Section.find(params[:id])
  end

  def require_authorized_for_current_course
    if current_course.user != current_user
      render text: 'Unauthorized', status: :Unauthorized
    end
  end

  # declares a helper method to Rails, which will let us call it in our views
  helper_method :current_course

  def current_course
    @current_course ||= Course.find(params[:course_id])
    # ^ line above is same as if/end statement below
    # basically says:
    #     if we've looked up the current_course beforehand,
    #     use the value that we looked up previously. If we haven't 
    #     looked up this course before, go into the database, 
    #     look it up and also make sure to remember the value in 
    #     case we need to look it up again later. This technique of storing 
    #     certain values inside of the memory to reduce the times we have to 
    #     find a certain value inside the database is called memoization

    # if @current_course == nil
    #   @current_course = Course.find(params[:course_id])
    #   @current_course
    # else
    #   @current_course
    # end
  end

  def section_params
    params.require(:section).permit(:title, :row_order_position)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/views/instructor/courses/new.html.erb
<div class="container">
  <div class="row">
    <div class="main-box">
      
      <h1>Add a New Course</h1>

      <%= simple_form_for @course, url: instructor_courses_path do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :cost %>
        <%= f.input :image %>
        <br />
        <%= f.submit "Create Course", class: "btn btn-pink" %>
        <br />
      <% end %>

    </div>
  </div>
</div>

app/views/instructor/courses/show.html.erb
<div class="container">
  <div class="row">
    <div class="main-box">

      <script>
        // drag-and-drop for Lessons
        $(function() {
          $('.lessons').sortable({
            update: function( event, ui ) {
              $.ajax({
                type: 'PUT',
                url: ui.item.data('update-url'),
                dataType: 'json',
                data: { lesson: { row_order_position: ui.item.index() } }
              });
              // alert("Lesson Id: " + ui.item.data('item-id') + " Update Url: " + ui.item.data('update-url') + " Index: " + ui.item.index());
            }
          });
        });

        // drag-and-drop for Sections
        $(function() {
          $('.sections').sortable({
            update: function(event, ui) {
              $.ajax({
                type: 'PUT',
                url: ui.item.data('update-url'),
                dataType: 'json',
                data: { section: { row_order_position: ui.item.index() } }
              });
              // alert("Section Id: " + ui.item.data('item-id') + " Update Url: " + ui.item.data('update-url') + " Index: " + ui.item.index());
            }
          });
        });

        // New Lesson button URL-passer
        $(function() {
          $('.new-lesson-button').click(function() {
            // alert( $(event.target).data('lesson-url') );
            var lessonUrl = $(event.target).data('lesson-url');
            $('#newLessonForm').attr('action', lessonUrl);
          });
        });
      </script>
      
      <h1>Manage this Course</h1>

      <h1 class="text-center"><%= current_course.title %></h1>
      <%= image_tag current_course.image, class: 'img-responsive courseimg' %>
      <br />

      <div class="text-center">
        <!-- Modal trigger button: Add Section -->
        <button type="button" class="btn btn-yellow btn-lg btn-space" data-toggle="modal" data-target="#modalAddSection">
          Add a New Section
        </button>
        &nbsp;
        <%= link_to 'Preview as Student', course_path(current_course), class: 'btn btn-pink btn-lg btn-space' %>
      </div>

      <ul class="sections">
        <% current_course.sections.rank(:row_order).each do |section| %>
          <li data-item-id=<%= section.id %> data-update-url=<%= instructor_section_path(section) %> class="sections-li">
            <div class="sections-title">
              <span class="glyphicon glyphicon-list"></span>
              <%= section.title %>
              <!-- Modal trigger button: Add Lesson -->
              <button type="button" class="btn btn-yellow btn-xs pull-right new-lesson-button" data-toggle="modal" data-target="#modalAddLesson" data-lesson-url=<%= instructor_section_lessons_path(section) %>>
                Add Lesson
              </button>
            </div>
            <ul class="lessons">
              <% section.lessons.rank(:row_order).each do |lesson| %>
                <li data-item-id=<%= lesson.id %> data-update-url=<%= instructor_lesson_path(lesson) %>>
                  <span class="glyphicon glyphicon-list"></span>
                  <h4 class="text-center"><%= lesson.title %></h4>
                  <hr />
                  <h5 class="text-center"><%= lesson.subtitle %></h5>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</div>



<!-- Modal: Add Section -->
<div class="modal fade" id="modalAddSection" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalAddSectionLabel">Add a New Section</h4>
      </div>
      <%= simple_form_for @section, url: instructor_course_sections_path(current_course) do |f| %>
          <div class="modal-body">
              <%= f.input :title %>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.submit "Add Section", class: 'btn btn-yellow' %>
          </div>
        <% end %>
    </div>
  </div>
</div>



<!-- Modal: Add Lesson -->
<div class="modal fade" id="modalAddLesson" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalAddLesonLabel">Add a New Lesson</h4>
      </div>
      <%= simple_form_for @lesson, url: "#", html: {id: 'newLessonForm'} do |f| %>
        <div class="modal-body">
            <%= f.input :title %>
            <%= f.input :subtitle %>
            <%= f.input :video %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Add Lesson", class: 'btn btn-yellow' %>
        </div>
      <% end %>
    </div>
  </div>
</div>