config/routes.rb
Flixter::Application.routes.draw do
  devise_for :users

  resource :dashboard, only: [:show]
  
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'

  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  
  resources :lessons, only: [:show]

  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update]

    resources :sections, only: [] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all.order(:id)
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show]

  def show
    # @course = Course.find(params[:id])
    #    ^ removed b/c we refactored @course into .current_course
    #      and now the view calls .current_course, so having it here
    #      would be redundant
    @section = Section.new
    #    ^ added when decided to move the new section form into a modal window
    #      on the instructor/courses#show page
    @lesson = Lesson.new
    #    ^ added when decided to move the new lesson form into a modal window
    #      on the instructor/courses#show page
  end

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end


  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render text: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_course

  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/views/courses/index.html.erb
<div class="container">
  <div class="row">
    <div class="main-box">

      <h1 class="text-center" id="callout">Learn something today</h1>

      <hr />

      <% @courses.each do |course| %>

        <h2 class="course-title text-center">
          <%= link_to course.title, course_path(course) %>
        </h2>
        <%= image_tag course.image, class: 'img-responsive courseimg' %>
        <br />
        <div class="col-sm-8 col-xs-12 course-desc">
          <%= course.description %>
        </div>
        <div class="col-sm-4 col-xs-12 text-center">
          <%= link_to 'More Details...', course_path(course), class: 'btn btn-pink btn-large' %>
        </div>

        <br class="clr" />

      <% end %>

    </div>
  </div>
</div>

app/views/courses/show.html.erb
<div class="container">
  <div class="row">
    <div class="main-box">

      <div class="col-xs-12 text-center">
        <h1><%= @course.title %></h1>
        <%= image_tag @course.image, class: 'img-responsive courseimg' %>

        <br />
      </div>

      <div class="col-sm-4 col-xs-12 text-center">
        <span class="label label-default cost">
          <%= number_to_currency @course.cost %>
        </span>

        <br />
        <br />
        
        <% if current_user && current_user.enrolled_in?(@course) %>
          <h3 class="label label-success cost">You are Enrolled!</h3>
        <% else %>
          <% if @course.free? %>
            <%= link_to 'Enroll', course_enrollments_path(@course), class: 'btn btn-pink', method: :post %>
          <% else %>

            <!-- begin Stripe button/form -->
            <%= form_tag course_enrollments_path(@course) do %>
              <article>
                <% if flash[:error].present? %>
                  <div id="error_explanation">
                    <p><%= flash[:error] %></p>
                  </div>
                <% end %>
              </article>

              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-description="<%= @course.title %> (<%= number_to_currency @course.cost %>)"
                      data-amount="<%= (@course.cost * 100).to_i %>"
                      data-locale="auto"></script>
            <% end %> 
            <!-- end Stripe button/form -->
            
          <% end %>
        <% end %>

        <br />
        <br />

        <% if current_user && current_user == @course.user %>
          <br />
          <%= link_to 'Administer this Course', instructor_course_path(@course), class: 'btn btn-yellow btn-large' %>
        <% end %>




      </div>

      <div class="col-sm-8 col-xs-12">
        <%= @course.description %>
      </div>


      <div class="col-xs-12">      

        <% @course.sections.rank(:row_order).each do |section| %>
          <div class="col-xs-12 section">
            <h3><%= section.title %></h3>
            
            <% section.lessons.rank(:row_order).each do |lesson| %>
              <%= link_to lesson_path(lesson) do %>
                <div class="col-sm-6 col-xs-12">
                  <div class="lesson text-center">
                    <h4><%= lesson.title %></h4>
                    <hr />
                    <h5><%= lesson.subtitle %></h5>
                  </div>
                </div>
              <% end %>
            <% end %>
            
          </div>
        <% end %>

      </div>

    </div>
  </div>
</div>