config/routes.rb
Flixter::Application.routes.draw do
  devise_for :users

  resource :dashboard, only: [:show]
  
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'

  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  
  resources :lessons, only: [:show]

  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update]

    resources :sections, only: [] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
  
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user
  has_many :sections
  has_many :enrollments

  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  mount_uploader :video, VideoUploader

  # pulls in the functionality of the gem to Lesson model
  include RankedModel
  # Lessons belong_to Sections, make the ranker scoped to one Section
  ranks :row_order, :with_same => :section_id

  # looks up the next lesson within it's section. If there is none, it will return nil
  def next_lesson
    # section - loads the section that is connected to the lesson we are "in"
    # .lessons - loads ALL the lessons that belong_to the loaded section
    # .where - allows us to add snippets of SQL that can filter records
    #     "row_order > ?" - says we're asking for records where row_order > ?, and ?
    #           indicates we will be passing through an additional value in a moment
    #     self.row_order - passes the row_order of the current lesson to the previous filter
    #     * in total, we're asking for records that come after the current lesson
    # .rank(:row_order) - sort the remaining lesson results by row_order
    # .first - takes the first lesson in the remaining list
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    # IF the lesson we just called is nil, meaning it is the last lesson in it's section
    # AND there is a truthy value when .next_section is called on the current section,
    # call .next_section on the current section, load all it's lessons, sort them by row_order
    # grab the first one, and return IT as the next_lesson
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
  has_many :lessons

  # pulls in the functionality of the gem to Section model
  include RankedModel
  # Sections belong_to Courses, make the ranker scoped to one Course
  ranks :row_order, :with_same => :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return section
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    ### original code
    # enrolled_courses = []
    # enrollments.each do |enrollment|
    #   enrolled_courses << enrollment.course
    # end

    ### refactored code (1st time)
    # enrolled_courses = enrollments.collect do |enrollment|
    #   enrollment.course
    # end

    ### refactored code (2nd time)
    # enrolled_courses = enrollments.collect(&:course)

    ### above line then removed because it is an N+1 query
    # and instead we added the has_many :through line above,
    # which is the exact same functionality but only makes ONE
    # call to the DB vs. N+1 calls

    return enrolled_courses.include?(course)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all.order(:id)
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  
  def show
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_course.premium?
      # Amount in cents
      #@amount = 500
      @amount = (current_course.cost * 100).to_i

      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Flower School (Premium Content)',
        :currency    => 'usd'
      )
    end

    current_user.enrollments.create(course: current_course)
    redirect_to course_path(current_course)

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to root_path
  end

  private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_lesson, only: [:show]

  def show
  end

  private


  # We have access to a lesson, which has access to a section, 
  # which has access to a course. In order words, something like 
  # current_lesson.section.course will give you access to a course 
  # if you have a lesson...
  def require_authorized_for_current_lesson
    #if current_lesson.section.course.user != current_user
    if !current_user.enrolled_in?(current_lesson.section.course)
      redirect_to course_path(current_lesson.section.course), alert: 'You must enroll in this course to access the lessons'
    end
  end

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def privacy
  end

  def team
  end

  def careers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Flower School</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!-- VideoJS include -->
  <link href="http://vjs.zencdn.net/5.10.7/video-js.css" rel="stylesheet">
  <!-- VideoJS include to support IE8 -->
  <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
</head>
<body>


  <!-- Fixed navbar -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Flower School', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'See all Courses', courses_path, id: 'seeall' %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to 'My Dashboard', dashboard_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>


  <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>


  <%= yield %>




  <br /><br />
  <!-- Sticky footer -->
  <footer class="footer">
    <div class="container footercontainer">
      <div class="row">
        <div class="col-md-3">
          <h6>Instructors</h6>
          <ul>
            <li><%= link_to 'Teach a Course', new_instructor_course_path %></li>
            <li><%= link_to 'View Dashboard', dashboard_path %></li>
          </ul>
        </div>
        <div class="col-md-3">
          <h6>About</h6>
          <ul>
            <li><%= link_to 'Team', team_path %></li>
            <li><%= link_to 'Careers', careers_path %></li>
            <li><%= link_to 'Privacy Policy', privacy_path %></li>
          </ul>
        </div>
        <div class="col-md-3">
          <h6>Contact</h6>
          <ul>
            <li>email@email.com</li>
          </ul>
        </div>
        <div class="col-md-3">
          <h6>Social</h6>
          <ul id="social-buttons">
            <li><%= link_to '#' do %>
              <%= image_tag 'icon_facebook.png' %>
            <% end %></li>
            <li><%= link_to '#' do %>
              <%= image_tag 'icon_instagram.png' %>
            <% end %></li>
            <li><%= link_to '#' do %>
              <%= image_tag 'icon_pinterest.png' %>
            <% end %></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>


</body>
</html>